routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| 
| 
| 
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('index');

/*
|--------------------------------------------------------------------------
| Auth Routes
|--------------------------------------------------------------------------
|
|
|
|
|
*/

Auth::routes();

Route::get('/verify/{token}', 'Auth\RegisterController@verify')->name('register.verify');

/*
|--------------------------------------------------------------------------
| Dashboard Routes
|--------------------------------------------------------------------------
|
| 
| 
| 
|
*/


Route::group([
    'prefix' => 'dashboard',
    ], function()
    {
        Route::get('/','Dashboard\DashboardController@index')->name('dashboard.index');
        Route::resource('/tasks', 'Dashboard\TaskController');
        Route::resource('/comments', 'Dashboard\CommentController');
        Route::resource('/users', 'Dashboard\UserController');
    });

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'confirmed' => 'boolean'
    ];

    public function confirm()
    {
        if ($this->confirmed) {
            throw new \DomainException("Mail already confirmed");            
        }        

        $this->confirmed = true;
        $this->confirmation_token = null;
        
        $this->save();
    }
}

app/Http/Controllers/Dashboard/CommentController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Requests\StoreCommentRequset;
use App\Http\Controllers\Controller;
use App\Comment;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Comment $comment, StoreCommentRequset $request)
    {
        $comment->content = $request->content;
        $comment->task_id = $request->task_id;
        $comment->save();

        return response()->json($comment);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Comment $comment)
    {
        $comment->content = $request->content;
        $comment->save();
        
        return response()->json($comment);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        $comment->delete();
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index()
    {
    	return view('dashboard.index');
    }
}

app/Http/Controllers/Dashboard/TaskController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Requests\StoreTaskRequset;
use App\Http\Controllers\Controller;
use App\Task;
use App\Status;
use App\Comment;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Task $task, Status $status)
    {
        $tasks = $task->latest()->with(['status', 'comments'])->withCount('comments')->get();
       
        return view('dashboard.tasks.index', [
            'title' => 'Задачи',
            'statuses' => $status->all(),
            'tasks' => $tasks,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Status $status)
    {
        return view('dashboard.tasks.create',[
            'title' => 'Добавление задачи',
            'statuses' => $status->all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTaskRequset $request, Task $task)
    {
        $task = $task->fill($request->taskFillData());
        $task->save();

        return redirect()->route('tasks.index')->with('status', __('messages.task.store'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task, Status $status)
    {
        return view('dashboard.tasks.edit', [
            'title' => 'Редактирование задачи',
            'task' => $task,
            'statuses' => $status->all(),
            'taskStatus' => $task->status,
            'comments' => $task->comments,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreTaskRequset $request, Task $task)
    {
        $task = $task->fill($request->taskFillData());
        $task->save();

        return redirect()->route('tasks.index')->with('status', __('messages.task.update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        $task->delete();
        
        return back()->with('status', __('messages.task.delete'));
    }
}

app/Http/Controllers/Dashboard/UserController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(User $user)
    {
        $users = $user->paginate(15);

        return view('dashboard.users.index', [
            'title' => 'Пользователи',
            'users' => $users,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.users.create', [
            'title' => 'Создать пользователя',
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, User $user)
    {
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt('secret');
        $user->save();
        
        return redirect()->route('users.index')
            ->with('status', __('messages.user.store'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('dashboard.users.edit', [
            'title' => 'Редактирование пользователя',
            'user' => $user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->name = $request->name;
        $user->email = $request->email;
        $user->update();
        
        return redirect()->route('users.index')
            ->with('status', __('messages.user.update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return back()->with('status', __('messages.user.delete'));
    }
}

resources/views/dashboard/users/create.blade.php
@extends('dashboard.layouts.app')

@section('content')

    <form method="post" action="{{ route('users.store') }}">

        @include('dashboard.users.form')

    </form>

@endsection

resources/views/dashboard/users/edit.blade.php
@extends('dashboard.layouts.app')

@section('content')

    <form method="post" action="{{ route('users.update', $user->id) }}">
    {{ method_field('PUT') }}
        @include('dashboard.users.form')

    </form>

@endsection

resources/views/dashboard/users/form.blade.php
    @csrf
    <div class="form-group col-md-8">

        {{ Form::label('InputUserName', 'Имя') }}

        {{ Form::text('name', $user->name ?? old('name'),
            array_merge([
            'class' => $errors->has('name') ? 'form-control is-invalid' : 'form-control'
            ],
            $attributes = [
                'id' => 'InputUserName',
                'aria-describedby' => 'InputUserNameHelp',
                'placeholder' => 'Имя'
            ])) }}

        @if ($errors->has('name'))
            <span class="invalid-feedback">
            <strong>{{ $errors->first('name') }}</strong>
            </span>
        @endif

        <small id="InputUserNameHelp" class="form-text text-muted">Имя пользователя</small>

    </div>

    <div class="form-group col-md-8">

        {{ Form::label('InputUserEmail', 'Email') }}

        {{ Form::text('email', $user->email ?? old('email'),
            array_merge([
            'class' => $errors->has('email') ? 'form-control is-invalid' : 'form-control'
            ],
            $attributes = [
                'id' => 'InputUserEmail',
                'aria-describedby' => 'InputUserEmailHelp',
                'placeholder' => 'E-Mail'
            ])) }}

        @if ($errors->has('email'))
            <span class="invalid-feedback">
            <strong>{{ $errors->first('email') }}</strong>
            </span>
        @endif

        <small id="InputUserEmailHelp" class="form-text text-muted">Почта пользователя</small>

    </div>

    

    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{{ route('users.index') }}" type="button" class="btn btn-primary">Отмена</a>

resources/views/dashboard/users/index.blade.php
@extends('dashboard.layouts.app')



@section('content')

    <main class="container pt-5">
        <div class="card mb-5 box-shadow">
            <div class="card-header">
                    <div class="row">
                        <div class="col col-xs-6">
                            <h3 class="panel-title">{{ $title or 'Нет заголовка' }}</h3>

                        </div>
                        <div class="col col-xs-6 text-right">
                            <a class="btn btn-sm btn-primary btn-create" href="{{ route('users.create') }}" role="button">Создать пользователя</a>
                        </div>
                    </div>


            </div>
            <div class="card-block p-0 table-responsive">
                <table class="table table-hover table-sm">
                    <thead class="">
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Потверждние почты</th>
                           
                            <th><em class="fa fa-cog"></em></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                       @forelse ($users as $user)
                        <tr>
                            <td class="hidden-xs">{{ $user->id }}</td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->confirmed ? 'Да' : 'Нет' }}</td>
                            
                            <td align="center">
                                <a class="btn btn-outline-success" href="{{ route('users.edit', $user->id) }}" title="Редактировать"><i class="fas fa-edit"></i></a>
                            </td>
                            <td>
                                

                                {!! Form::open(['method' => 'DELETE','route' => [
                                    'users.destroy', $user->id],
                                    'style'=>'display:inline'
                                    ]) !!}
                                {!! Form::button('<i class="fa fa-trash fa-lg"></i>', [
                                    'class' => 'btn btn-danger',
                                    'data-toggle' => 'confirmation',
                                    'data-title' => 'Вы уверены?',
                                    'data-btn-ok-label' => 'Да',
                                    'data-btn-cancel-label' => 'Нет',
                                    'data-popout' => 'true',
                                    'data-singleton' => 'true',
                                    ]) !!}
                                {!! Form::close() !!}

                            </td>
                        
                        </tr>
                        @empty
                            <td class="table-warning" colspan="7"  style="text-align:center">Empty</td>
                        @endforelse
                    </tbody>
                </table>
            </div>
            <div class="card-footer p-3">
                {{ $users->links() }}
            </div>
        </div>
        
    </main>


@endsection