routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| 
| 
| 
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('index');

/*
|--------------------------------------------------------------------------
| Auth Routes
|--------------------------------------------------------------------------
|
|
|
|
|
*/

Auth::routes();

Route::get('/verify/{token}', 'Auth\RegisterController@verify')->name('register.verify');

/*
|--------------------------------------------------------------------------
| Dashboard Routes
|--------------------------------------------------------------------------
|
| 
| 
| 
|
*/


Route::group([
    'prefix' => 'dashboard',
    ], function()
    {
        Route::get('/','Dashboard\DashboardController@index')->name('dashboard.index');
        Route::resource('/tasks', 'Dashboard\TaskController');
        Route::resource('/comments', 'Dashboard\CommentController');
        Route::resource('/users', 'Dashboard\UserController');
    });

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = [
        'title', 'description', 'status_id',
    ];

    public function status()
    {
        return $this->belongsTo(Status::class, 'status_id', 'id');
    }

    public function comments()
    {
    	return $this->hasMany(Comment::class, 'task_id', 'id');
    }
}

app/Http/Controllers/Dashboard/CommentController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Requests\StoreCommentRequset;
use App\Http\Controllers\Controller;
use App\Comment;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Comment $comment, StoreCommentRequset $request)
    {
        $comment->content = $request->content;
        $comment->task_id = $request->task_id;
        $comment->save();

        return response()->json($comment);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Comment $comment)
    {
        $comment->content = $request->content;
        $comment->save();
        
        return response()->json($comment);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        $comment->delete();
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index()
    {
    	return view('dashboard.index');
    }
}

app/Http/Controllers/Dashboard/TaskController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Requests\StoreTaskRequset;
use App\Http\Controllers\Controller;
use App\Task;
use App\Status;
use App\Comment;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Task $task, Status $status)
    {
        $tasks = $task->latest()->with(['status', 'comments'])->withCount('comments')->get();
       
        return view('dashboard.tasks.index', [
            'title' => 'Задачи',
            'statuses' => $status->all(),
            'tasks' => $tasks,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Status $status)
    {
        return view('dashboard.tasks.create',[
            'title' => 'Добавление задачи',
            'statuses' => $status->all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTaskRequset $request, Task $task)
    {
        $task = $task->fill($request->taskFillData());
        $task->save();

        return redirect()->route('tasks.index')->with('status', __('messages.task.store'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task, Status $status)
    {
        return view('dashboard.tasks.edit', [
            'title' => 'Редактирование задачи',
            'task' => $task,
            'statuses' => $status->all(),
            'taskStatus' => $task->status,
            'comments' => $task->comments,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreTaskRequset $request, Task $task)
    {
        $task = $task->fill($request->taskFillData());
        $task->save();

        return redirect()->route('tasks.index')->with('status', __('messages.task.update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        $task->delete();
        
        return back()->with('status', __('messages.task.delete'));
    }
}

app/Http/Controllers/Dashboard/UserController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(User $user)
    {
        $users = $user->paginate(15);

        return view('dashboard.users.index', [
            'title' => 'Пользователи',
            'users' => $users,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.users.create', [
            'title' => 'Создать пользователя',
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, User $user)
    {
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt('secret');
        $user->save();
        
        return redirect()->route('users.index')
            ->with('status', __('messages.user.store'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('dashboard.users.edit', [
            'title' => 'Редактирование пользователя',
            'user' => $user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->name = $request->name;
        $user->email = $request->email;
        $user->update();
        
        return redirect()->route('users.index')
            ->with('status', __('messages.user.update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return back()->with('status', __('messages.user.delete'));
    }
}

resources/views/dashboard/tasks/create.blade.php
@extends('dashboard.layouts.app')

@section('content')

    <form method="post" action="{{ route('tasks.store') }}">

        @include('dashboard.tasks.form')

    </form>

@endsection

resources/views/dashboard/tasks/edit.blade.php
@extends('dashboard.layouts.app')

@section('content')

    <form method="post" action="{{ route('tasks.update', $task->id) }}">
    {{ method_field('PUT') }}
		@include('dashboard.tasks.form')
	</form>


@include('dashboard.comments.form')

@endsection

resources/views/dashboard/tasks/form.blade.php
    @csrf
    <div class="form-group col-md-8">
        
        {{ Form::label('InputTaskTitle', 'Заголовок') }}

        {{ Form::text('title', $task->title ?? old('title'),
            array_merge([
            'class' => $errors->has('title') ? 'form-control is-invalid' : 'form-control'
            ],
            $attributes = [
                'id' => 'InputTaskTitle',
                'aria-describedby' => 'InputTaskTitleHelp',
                'placeholder' => 'Заголовок'
            ])) }}

        @if ($errors->has('title'))
            <span class="invalid-feedback">
                <strong>{{ $errors->first('title') }}</strong>
            </span>
        @endif

        <small id="InputTaskTitleHelp" class="form-text text-muted">Заголовок задачи</small>
    </div>

    <div class="form-group col-md-8">

        {{ Form::label('InputTaskDescription', 'Описание задачи') }}

        {{ Form::textarea('description', $task->description ?? old('description'),
            array_merge([
                'class' => $errors->has('description') ? 'form-control is-invalid' : 'form-control'
            ],
            $attributes = [
                'id' => 'InputTaskDescription',
                'aria-describedby' => 'InputTaskDescriptionHelp',
                'placeholder' => 'Описание'
            ])) }}

        @if ($errors->has('description'))
            <span class="invalid-feedback">
                <strong>{{ $errors->first('description') }}</strong>
            </span>
        @endif

        <small id="InputTaskDescriptionHelp" class="form-text text-muted">Короткое описание задачи</small>

    </div>

    <div class="form-group col-md-4">

        {{ Form::label('InputStatus', 'Статус задачи') }}

        @if (count($statuses) !== 0)
            {!! Form::select('status_id', 
                $statuses->pluck('title','id'),
                $task->status->id ?? null,
                [
                    'class' => 'form-control',
                    'id' => 'InputStatus'
                    ]) !!}
        @else
            <div class="alert alert-info" role="alert">
                <h5 class="alert-heading">Необходимо создать статус.</h5>
            </div>
        @endif

    </div>
    
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{{ route('tasks.index') }}" type="button" class="btn btn-primary">Отмена</a>

resources/views/dashboard/tasks/index.blade.php
@extends('dashboard.layouts.app')

@section('content')

<a class="btn btn-success btn-lg btn-block" href="{{ route('tasks.create') }}" role="button">Создать задачу</a>
<br>
<div class="row">
    @forelse ($statuses as $status)
        <div class="col-sm-4">
            <div class="card">
              <div class="card-header bg-secondary">
                {{ $status->title }}
              </div>
              @forelse ($tasks as $task)
                <ul class="list-group list-group-flush">
                  @if ($status->id === $task->status_id)
                  <li class="list-group-item">
                      <h5 class="card-title">{{ $task->title }}</h5>
                      <p class="card-text">{{ $task->description }}</p>
                      <p class="card-text">Комментариев: {{ $task->comments_count }}</p>
                      <p class="card-text"><small class="text-muted">Создано: {{ $task->created_at ? $task->created_at->diffForHumans() : 'Нет даты добавления' }}</small></p>
                      <p class="card-text"><small class="text-muted">Обновлено: {{ $task->updated_at ? $task->updated_at->diffForHumans() : 'Нет даты обновления' }}</small></p>
                      <a class="btn btn-outline-success btn-block" href="{{ route('tasks.edit', $task->id) }}" title="Редактировать"><i class="fas fa-edit"></i></a>
                      <form action="{{ route('tasks.destroy', $task->id) }}" method="post">
                              {{ csrf_field() }}
                              {{ method_field('delete') }}
                              <button class="btn btn-outline-dark btn-block" onclick="return confirm('Хотите удалить?')" type="submit" title="Удалить"><i class="fas fa-trash-alt"></i></button>
                      </form>
                  </li>
                  @endif
                </ul>
              @empty
                <div class="alert alert-info" role="alert">
                  <h5 class="alert-heading">Нет записей</h5>
                </div>
              @endforelse
            </div>
        </div>
    @empty
      <div class="alert alert-info" role="alert">
        <h5 class="alert-heading">Нет записей</h5>
      </div>
    @endforelse
</div>

@endsection